task:
  freebsd_instance:
    cpu: 2
    memory: 8G
    matrix:
      # image: freebsd-12-1-release-amd64 # EOL
      - image: freebsd-12-2-release-amd64
      # image: freebsd-13-0-current-amd64-v20201112 # Image way too large, HIDPI broken and iichid trackpad broken on Acer

  env:
    CIRRUS_CLONE_DEPTH: 1
    GITHUB_TOKEN: ENCRYPTED[!0f42e3f70fd51cdeddfe7e98160982fc9efe7e8a26869b725fcd5de05d067a7100b994cf52f0f1b470a983148e0b8ec2!]
    APPLICATION_NAME="Scribus"
    PACKAGE_NAMES=scribus-devel
    EXECUTABLE_NAME=scribus
    
  auto_cancellation: false
  stateful: false
  timeout_in: 60m
  # only_if: $CIRRUS_TAG !=~ 'continuous.*'
  # Do not build tags, only commits
  only_if: $CIRRUS_TAG !=~ '..*'

  env:
    matrix:
      arch: 'amd64'

  Environment_script:
    - env
    - kldload zfs.ko
    - kldload tmpfs.ko || true
    - kldload nullfs.ko || true
    - kldload geom_uzip.ko || true
    - pkg install -y pkg git-lite zsync wget sha bash zip devel/py-xdg librsvg2 ca_root_nss sudo ImageMagick7-nox11 # qemu-devel uefi-edk2-qemu-x86_64
    
  Build_script:
    - wget -c https://github.com/$(wget -q https://github.com/helloSystem/ISO/releases/tag/experimental-12.2 -O - | grep "hello-.*.amd64.iso.pkg.zip" | head -n 1 | cut -d '"' -f 2)
    - mv usr/local/furybsd/uzip/var/db/pkg /var/db/pkg.pristine
    - mkdir -p artifacts/
    - sh ./makebundle
    - mv *.zip artifacts/
    - ls -lh "${CIRRUS_WORKING_DIR}"/artifacts/*.zip || false # Error out if zip was not produced to mitigate the above
    
  Upload_script:
    - export VER=$(uname -r | cut -d "-" -f 1) # No way to pass on from Build_script to Upload_script?
    - ls -lh "${CIRRUS_WORKING_DIR}"/artifacts/
    - case "$CIRRUS_BRANCH" in *pull/*) echo skipping since PR ;; * ) wget -c -q https://github.com/tcnksm/ghr/files/5247714/ghr.zip ; unzip ghr.zip ; ./ghr -prerelease -delete -t "${GITHUB_TOKEN}" -u "${CIRRUS_REPO_OWNER}" -r "${CIRRUS_REPO_NAME}" -b "This is an experimental __UNTESTED__ build for developers." -c "${CIRRUS_CHANGE_IN_REPO}" "$APPLICATION_NAME" "${CIRRUS_WORKING_DIR}"/artifacts ; esac
