task:
  freebsd_instance:
    cpu: 2
    memory: 8G
    matrix:
      # image: freebsd-12-2-release-amd64
      - image: freebsd-13-0-release-amd64

  env:
    USER: 1000
    CIRRUS_CLONE_DEPTH: 1
    GITHUB_TOKEN: ENCRYPTED[!0f42e3f70fd51cdeddfe7e98160982fc9efe7e8a26869b725fcd5de05d067a7100b994cf52f0f1b470a983148e0b8ec2!]
    APPLICATION_NAME: Firefox
    PACKAGE_NAMES: firefox
    EXECUTABLE_NAME: firefox
    
  auto_cancellation: false
  stateful: false
  timeout_in: 60m
  # only_if: $CIRRUS_TAG !=~ 'continuous.*'
  # Do not build tags, only commits
  only_if: $CIRRUS_TAG !=~ '..*'

  env:
    matrix:
      arch: 'amd64'

  Environment_script:
    - env
    - kldload zfs.ko
    - kldload tmpfs.ko || true
    - kldload nullfs.ko || true
    - kldload geom_uzip.ko || true
    - pkg install -y pkg wget sha zip patchelf ca_root_nss sudo ImageMagick6 # ImageMagick7-nox11
    
  Build_script:
    - mkdir -p work
    - mount -t tmpfs tmpfs ./work
    - cd work
    - wget -c https://github.com/$(wget -q https://github.com/helloSystem/ISO/releases/tag/experimental-13.0 -O - | grep "hello-.*.amd64.iso.pkg.zip" | head -n 1 | cut -d '"' -f 2)
    - unzip *.iso.pkg.zip
    - mv usr/local/furybsd/uzip/var/db/pkg /var/db/pkg.pristine
    - mkdir -p artifacts/
    - sh -ex ../makebundle
    - mkdir -p artifacts ; mv "${APPLICATION_NAME}"*img artifacts/
    
  Upload_script:
    - export VER=$(uname -r | cut -d "-" -f 1) # No way to pass on from Build_script to Upload_script?
    - ls -lh "${CIRRUS_WORKING_DIR}"/work/artifacts/
    - export RELEASE_NAME=$(echo "$APPLICATION_NAME" | sed -e 's| |_|g') # GitHub Release names cannot contain blanks
    - case "$CIRRUS_BRANCH" in *pull/*) echo skipping since PR ;; * ) wget -c -q https://github.com/tcnksm/ghr/files/5247714/ghr.zip ; unzip ghr.zip ; ./ghr -prerelease -delete -t "${GITHUB_TOKEN}" -u "${CIRRUS_REPO_OWNER}" -r "${CIRRUS_REPO_NAME}" -b "This is an experimental __UNTESTED__ build for developers." -c "${CIRRUS_CHANGE_IN_REPO}" "$RELEASE_NAME" "${CIRRUS_WORKING_DIR}"/work/artifacts ; esac
